FROM grafana/grafana:latest

USER root

# Certifique-se de que o diretório `provisioning/dashboards` existe antes de copiá-lo
RUN mkdir -p /var/lib/grafana/provisioning/dashboards /var/lib/grafana/provisioning/datasources

# Copiar os arquivos para o diretório correto
COPY provisioning/datasource.yml /var/lib/grafana/provisioning/datasources/
COPY provisioning/dashboard.yml /var/lib/grafana/provisioning/dashboards/
COPY dashboards/mariadb_dashboard.json /var/lib/grafana/provisioning/dashboards/

# Garantir permissões para o usuário grafana
RUN chown -R 472:472 /var/lib/grafana/provisioning

USER grafana
